specVersion: 0.0.1
description: Indexer for moonriver staking
repository: git@github.com:Moehringen/moonriverindexer.git
schema: ./schema.graphql
network:
  #endpoint: wss://wss.moonriver.moonbeam.network
  #endpoint: wss://moonriver.api.onfinality.io/ws?apikey=70d75730-8f86-4ea4-924e-28579479531f
  #endpoint: wss://service.elara.patract.io/Moonriver/68a73896e0e22cfaa474099b4beb4087
  #dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
  #shmily1140
  endpoint: wss://moonriver.api.onfinality.io/ws?apikey=a1e8511f-3c84-4fd6-8439-b6b8edfb5884
  #dedicated:
  #endpoint: wss://node-6852438962031144960.jm.onfinality.io/ws?apikey=3f466a1e-c0ee-4996-b345-4d01f454fdad
  #Bwarelabs:
  #endpoint: wss://moonriver-api.bwarelabs.com/ws/afe7985e-fe12-4a21-9fcc-c2749326e9b8
  types:
      AccountId: EthereumAccountId
      Address: AccountId
      Balance: u128
      RefCount: u8
      LookupSource: AccountId
      Account: 
        nonce: U256
        balance: u128
      RewardInfo: 
        totalReward: Balance
        claimedReward: Balance
        contributedRelayAddresses: Vec<RelayChainAccountId>
      VestingBlockNumber: u32
      NominatorStatus: 
        _enum: 
          Active: "Null"
          Leaving: RoundIndex
      Nominator2: 
        nominations: Vec<Bond>
        revocations: Vec<AccountId>
        total: Balance
        scheduledRevocationsCount: u32
        scheduledRevocationsTotal: Balance
        status: NominatorStatus
      ExitQ: 
        candidates: Vec<AccountId>
        nominatorsLeaving: Vec<AccountId>
        candidateSchedule: Vec<(AccountId, RoundIndex)>
        nominatorSchedule: Vec<(AccountId, Option<AccountId>, RoundIndex)>
      EthereumSignature: 
        r: H256
        s: H256
        v: U8 
      Collator2: 
        id: AccountId
        bond: Balance
        nominators: Vec<AccountId>
        topNominators: Vec<Bond>
        bottomNominators: Vec<Bond>
        totalCounted: Balance
        totalBacking: Balance
        state: CollatorStatus
      NominatorAdded: 
        _enum: 
          AddedToTop: Balance 
          AddedToBottom: "Null"
      RegistrationInfo: 
        account: AccountId
        deposit: Balance
      ParachainBondConfig: 
        account: AccountId
        percent: Percent
      AccountId32: H256
      AuthorId: AccountId32
      RelayChainAccountId: AccountId32
      AccountInfo: AccountInfoWithTripleRefCount
      Candidate: 
        id: AccountId
        fee: Perbill
        bond: Balance
        nominators: Vec<Bond>
        total: Balance
        state: CollatorStatus 
      CollatorStatus: 
        _enum: 
          Active: "Null"
          Idle: "Null"
          Leaving: RoundIndex
      Range: RangeBalance
      RangeBalance: 
        min: Balance
        ideal: Balance
        max: Balance
      RangePerbill: 
        min: Perbill
        ideal: Perbill
        max: Perbill
      InflationInfo: 
        expect: RangeBalance
        annual: RangePerbill
        round: RangePerbill
      OrderedSet: Vec<Bond>
      Collator: 
        id: AccountId
        bond: Balance
        nominators: Vec<Bond>
        total: Balance
        state: CollatorStatus
      CollatorSnapshot: 
        bond: Balance
        nominators: Vec<Bond>
        total: Balance
      SystemInherentData: 
        validation_data: PersistedValidationData
        relay_chain_state: StorageProof
        downward_messages: Vec<InboundDownwardMessage>
        horizontal_messages: BTreeMap<ParaId, Vec<InboundHrmpMessage>>
      RoundInfo: 
        current: RoundIndex
        first: BlockNumber
        length: u32
      ExtrinsicSignature: EthereumSignature
      RoundIndex: u32
      Nominator: 
        nominations: Vec<Bond>
        total: Balance
      Bond: 
        owner: AccountId
        amount: Balance
      ValidatorStatus: 
        _enum: 
          Active: "Null"
          Idle: "Null"
          Leaving: RoundIndex 
      TxPoolResultContent: 
        pending: HashMap<H160, HashMap<U256, PoolTransaction>>
        queued: HashMap<H160, HashMap<U256, PoolTransaction>>
      TxPoolResultInspect: 
        pending: HashMap<H160, HashMap<U256, Summary>>
        queued: HashMap<H160, HashMap<U256, Summary>>
      TxPoolResultStatus: 
        pending: U256
        queued: U256
      Summary: Bytes
      PoolTransaction: 
        hash: H256
        nonce: U256
        block_hash: Option<H256>
        block_number: Option<U256>
        from: H160
        to: Option<H160>
        value: U256
        gas_price: U256
        gas: U256
        input: Bytes
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 0
    mapping:
      handlers:
        #- handler: handleRoundCreated
        #  kind: substrate/EventHandler
        #  filter:
        #    module: parachainStaking
        #    method: NewRound
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
